### ISSUE TITLE
Error in phising url

### ISSUE THREAD

**Issue by saahilwaze** [OnlineHacKing/PUBG-Phishing#3]
Hello, when I create a URL it doesn't works and at the end of url comes @error. 
![Screenshot_20210324-123514](https://user-images.githubusercontent.com/78599075/112268950-be932300-8c9d-11eb-869a-34a684953958.jpg)

**Comment by OnlineHacKing** [comment]
your setup not complete

**Comment by OnlineHacKing** [comment]
and update this tool

**Comment by OnlineHacKing** [comment]
setup now and ngrok token enter now
