### ISSUE TITLE
Worked Hard on the latest Update but...

### ISSUE THREAD

**Issue by Devilemox** [OnlineHacKing/PUBG-Phishing#6]
Thanks for updating the script and i loved the work but You maybe forgot to update the web pages. They are outdated. On the last issue i was telling you to make the webpages dynamic, So that you don't have to worry about the Current Season and there will be no need to manually update them. Do Something About this if you can.

Thanks For the Work Anyways. :)
![Screenshot from 2021-05-10 23-41-10](https://user-images.githubusercontent.com/43777071/117660706-1ee11400-b1bb-11eb-915d-3a370fb4a1db.png)

**Comment by Cyber-Warrior-6** [comment]
bro where passwords are saved? Do you know ?

**Comment by Devilemox** [comment]
There will be a folder where all the logs will be saved.

**Comment by OnlineHacKing** [comment]
install new v 2.4 pubg and bgmi s19 update
